# Generated by Django 3.2.6 on 2024-04-16 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_city'),
        ('users', '0010_auto_20240415_2159'),
    ]

    operations = [
    ]
