# Generated by Django 3.2.6 on 2024-04-17 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20240416_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(default='', max_length=35, verbose_name='city'),
        ),
    ]
