version: '3.8'

services:


  db:
    image: postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: ${POSTGRES_HOST_AUTH_METHOD}
      PG_DATA: /var/vib/postgresql/data/pgdata
    volumes:
      - pg_data:/var/vib/postgresql/data/pgdata
    ports:
      - '5434:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    tty: true
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - '8000:8000'
    volumes:
      - .:/code
    depends_on:
      db:
        condition: service_healthy

  test:
    build: .
    command: python manage.py test
    volumes:
      - .:/code
    depends_on:
      - db

  coverage:
    build: .
    command: bash -c "coverage run --source='.' manage.py test && coverage report"
    volumes:
      - .:/code
    depends_on:
      - db

volumes:
  pg_data:


